version: '3'
services:
  craw:
    build:
      context: .
      dockerfile: Craw/CrawDockerfile
    container_name: craw-data
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.env:/app/.env:ro
      - ./models:/app/models
      - ./crawing-data:/app/crawing-data
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - CRAWING_TARGET=KQXSVN
      #,KQXSVNFirstSpecial
      # - CRAWING_START_DATE=2024-06-19
      # - CRAWING_END_DATE=2024-06-19
