version: '3'
services:
  tele:
    image: lotteryai_common
    container_name: tele-notify
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .envcp:/app/.env:ro
      - ./models:/app/models
      - ./crawing-data:/app/crawing-data
      - ./data:/app/data
    command: python -m Tele.TeleMessage
    # environment:
    #   - PREDICT_DATE=2024-09-30
