version: '3'
services:
  tele_first:
    image: lotteryai_common
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .envcp:/app/.env:ro
      - ./models_first:/app/models
      - ./crawing-data:/app/crawing-data
      - ./data:/app/data
    networks:
      - tele_first
    command: python -m Tele.TeleMessageFirst
    # environment:
    #   - PREDICT_DATE=2024-06-20

networks:
  tele_first:
    driver: bridge
