version: '3'
services:
  train:
    image: lotteryai_common
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./models:/app/models
      - ./crawing-data:/app/crawing-data
    environment:
      - CHANELS=ben-tre
    networks:
      - train

networks:
  train:
    driver: bridge

